before: 'docker-compose -f docker-compose.yml run -T golang sh -xc "go version" && docker ps -a'
sub_build_tag: dotci
run:
  golang: 'sh -xc "go version"'
  node: 'sh -xc "node -v"'
  node2: 'sh -xc "echo test2"'